language: R
cache: packages

services:
  - docker

r:
  - release
#  - oldrel
  - devel

sudo: required
dist: xenial

# don't do vignettes (relevant when trying to get on CRAN)
r_build_args: "--no-manual --no-build-vignettes"
r_check_args: "--no-manual --ignore-vignettes" # --as-cran
